export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  USERS_NEW: "/users/new",
  MERCHANT_EMPLOYEES: "/merchant/employees",
  BUSINESS_PARTNERS: "/business-partners",
  BUSINESS_PARTNER_DETAIL: "/business-partners/:id",
  CATEGORIES: "/categories",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",
  PRODUCT_GROUPS: "/product-groups",
  PRODUCT_GROUP_DETAIL: "/product-groups/:id",
  BP_ASSIGNMENTS: "/bp-assignments",
  EMPLOYEE_PRODUCTS: "/employee/products",
  EMPLOYEE_PRODUCT_GROUPS: "/employee/product-groups",
  HOMEPAGE: "/homepage",
  WHATSAPP_TEMPLATES: "/whatsapp-templates",
  BRANDING: "/branding",
  FIELD_VISIBILITY: "/field-visibility",
  SKU_MANAGEMENT: "/sku-management",
  SKU_MANAGEMENT_NEW: "/sku-management/new",
  SKU_MANAGEMENT_CLEANUP: "/sku-management/cleanup",
  SKU_MANAGEMENT_DROPDOWNS: "/sku-management/dropdowns",
  SKU_MANAGEMENT_TEMPLATES: "/sku-management/templates",
  SETTINGS: "/settings",
  CREATE_PDF: "/create-pdf",
  CREATE_PDF_TEMPLATE_NEW: "/create-pdf/templates/new",
  CREATE_PDF_TEMPLATE_EDIT: "/create-pdf/templates/$templateId",
  CREATE_PDF_CUSTOMIZE: "/create-pdf/customize/$templateId",
  /** PDFium-engine editor, running alongside CREATE_PDF_CUSTOMIZE while it
   * is brought up to feature parity. Not linked from the UI yet — reached
   * by URL during development. */
  CREATE_PDF_CUSTOMIZE_V2: "/create-pdf/customize-v2/$templateId",
  AI_IMAGES: "/ai-images",
  EXTRACT_PRODUCT_PDF: "/extract-product-pdf",
} as const
