export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  USERS_NEW: "/users/new",
  MERCHANT_EMPLOYEES: "/merchant/employees",
  BUSINESS_PARTNERS: "/business-partners",
  BUSINESS_PARTNER_DETAIL: "/business-partners/:id",
  CATEGORIES: "/categories",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",
  PRODUCT_GROUPS: "/product-groups",
  PRODUCT_GROUP_DETAIL: "/product-groups/:id",
  BP_ASSIGNMENTS: "/bp-assignments",
  EMPLOYEE_PRODUCTS: "/employee/products",
  EMPLOYEE_PRODUCT_GROUPS: "/employee/product-groups",
  HOMEPAGE: "/homepage",
  WHATSAPP_TEMPLATES: "/whatsapp-templates",
  BRANDING: "/branding",
  FIELD_VISIBILITY: "/field-visibility",
  SETTINGS: "/settings",
} as const
