networks:
  custom_trabelci_network:
    external: true

services:
  admin:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_ADMIN_API_BASE_URL: ${VITE_ADMIN_API_BASE_URL}
        VITE_ROOM_VISUALIZER_URL: ${VITE_ROOM_VISUALIZER_URL}
    container_name: admin-panel
    networks:
      - custom_trabelci_network
    ports:
      - "5173:80"
    restart: unless-stopped

